### ISSUE TITLE
Is the solution bottlenecked by a max file size or does it chunk?

### ISSUE THREAD

**Issue by frostebite** [troyready/git-lfs-s3#57]

**Comment by troyready** [comment]
@frostebite at the moment it's limited to 5GB files due to [the design of Git LFS's basic transfer API](https://github.com/git-lfs/git-lfs/blob/v3.3.0/docs/api/basic-transfers.md#uploads) -- the Git LFS client expects to get a single URL to which it can upload.

If the [proposed Multipart transfer mode](https://github.com/git-lfs/git-lfs/blob/3fa66a63f3f62671a15e6cecbcfb306520ee7318/docs/proposals/multipart_transfer_mode.md) is implemented then I'm sure this can be updated to support it.

The other option in the interim would be to add support for [giftless's custom multipart mode](https://giftless.datopian.com/en/latest/multipart-spec.html) and then using [their Git LFS client](https://github.com/datopian/giftless-client). I'd be open to a PR adding server support for that.
